export const items = [
  {
    Id: 1,
    Name: "Shuriken Race",
    ResourceType: 0,
    TimeStamp: 1787606104,
    AuthorId: 0,
    AuthorName: "Adifo",
    PreviewUri: "/previews/shuriken-race.jpg",
    PayloadUri: "/payloads/shuriken-race.zip",
    Description: "A custom Marble Race level.",
    PayloadLength: 385028,
    Version: "0.0",
    Tags: ["shuriken", "race"],
    Downloads: 0,
    Rating: 0,
  },
  {
    Id: 990000000001,
    Name: "Hamsterball V 2.4.2",
    ResourceType: 2,
    TimeStamp: 1787672863,
    AuthorId: 0,
    AuthorName: "Many People",
    PreviewUri: "/previews/hamsterball-v-2-4-2.png",
    PayloadUri: "https://raw.githubusercontent.com/kkuhn317/marble-race-workshop/main/release-assets/hamsterball-v-2-4-2.zip",
    Description: "This campaign includes all of the levels in the original Hamsterball game, including secret medal times and different arena unlock locations.",
    PayloadLength: 39955236,
    Version: "1.5.3",
    Tags: ["hamsterball", "campaign", "recreation"],
    Downloads: 0,
    Rating: 0,
  },
  {
    Id: 990000000002,
    Name: "Kry Pack 2",
    ResourceType: 2,
    TimeStamp: 1787672863,
    AuthorId: 0,
    AuthorName: "Kry",
    PreviewUri: "/previews/kry-pack-2.jpg",
    PayloadUri: "https://raw.githubusercontent.com/kkuhn317/marble-race-workshop/main/release-assets/kry-pack-2.zip",
    Description: "Official sequel to Kry Pack.",
    PayloadLength: 46581716,
    Version: "1.5.3",
    Tags: ["campaign", "kry"],
    Downloads: 0,
    Rating: 0,
  },
  {
    Id: 990000000003,
    Name: "Interlude",
    ResourceType: 0,
    TimeStamp: 1787672863,
    AuthorId: 0,
    AuthorName: "lunosomnia",
    PreviewUri: "/previews/interlude.png",
    PayloadUri: "/payloads/interlude.zip",
    Description: "A custom Marble Race level by lunosomnia.",
    PayloadLength: 922957,
    Version: "1.4.17",
    Tags: ["level", "race"],
    Downloads: 0,
    Rating: 0,
  },
  {
    Id: 990000000004,
    Name: "The Embered Racing",
    ResourceType: 0,
    TimeStamp: 1787672863,
    AuthorId: 0,
    AuthorName: "Mikey",
    PreviewUri: "/previews/the-embered-racing.png",
    PayloadUri: "/payloads/the-embered-racing.zip",
    Description: "There are bowling-ball enemies on the yellow danger zones. Roll carefully: they will catch and push you.",
    PayloadLength: 2921688,
    Version: "1.5.3",
    Tags: ["level", "race", "bowling balls"],
    Downloads: 0,
    Rating: 0,
  },
];

export function json(value, status = 200) {
  return new Response(JSON.stringify(value), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "access-control-allow-origin": "*",
      "cache-control": "no-store",
    },
  });
}

export function publicItem(item, requestUrl) {
  const origin = new URL(requestUrl).origin;
  return {
    Id: item.Id,
    Name: item.Name,
    ResourceType: item.ResourceType,
    TimeStamp: item.TimeStamp,
    AuthorId: item.AuthorId,
    AuthorName: item.AuthorName,
    PreviewUri: new URL(item.PreviewUri, origin).toString(),
    PayloadUri: new URL(item.PayloadUri, origin).toString(),
    Description: item.Description,
    PayloadLength: item.PayloadLength,
    Version: item.Version,
  };
}
